### PR TITLE
fix: prevent promptEditorHelper to run if running tests in vscode

### LINKED ISSUE #4862: Running tests in vscode triggers the promptEditorHelper
### Describe the bug

For local development of `netlify/cli` while running tests `npm run test` in the vscode terminal, the `promptEditorHelper` function is triggered. You can see `Would you like to configure VS Code to use Edge Functions? (Y/n)` in the test logs.

### Steps to reproduce

1. Run `npm run test` from a terminal in vscode
2. Check the logs

### Configuration

_No response_

### Environment

From a vscode environment

### PR DESCRIPTION
**Pull request by khendrikse**
#### Summary

Fixes #4862 

Added a check for test environment inside the `promptEditorHelper` function. This decision was made based upon the thought that we could either change the `env.TERM_PROGRAM` in all tests, or check if the `env.NODE_ENV` was `test`.

---

For us to review and ship your PR efficiently, please perform the following steps:

- [x] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [x] Update or add tests (if any source code was changed or added) 🧪
- [x] Update or add documentation (if features were changed or added) 📝
- [x] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

### CODE REVIEW

File: src/lib/edge-functions/editor-helper.js [hunk 1]
```diff
@@ -7,6 +7,7 @@ const { runRecipe } = require('../../commands/recipes')
 const STATE_PROMPT_PROPERTY = 'promptVSCodeSettings'
 
 const promptEditorHelper = async ({ NETLIFYDEVLOG, chalk, config, log, repositoryRoot, state }) => {
+  if (env.NODE_ENV === 'test') return
```
Comment (eduardoboucas) [inline src/lib/edge-functions/editor-helper.js:10]: I think it'd be good to add a comment to clarify the intent here.

```suggestion
  // This prevents tests from hanging when running them inside the VS Code
  // terminal, as otherwise we'll show the prompt and wait for a response.
  if (env.NODE_ENV === 'test') return
    
```

**Review by eduardoboucas — APPROVED** [review]

**Review by danez — DISMISSED** [review]
LGTM, thanks for looking into this.

**Review by danez — APPROVED** [review]
🚀
