### PR TITLE
fix: added missing mock geo data

### LINKED ISSUE #5232: Add missing mock geo data
## Description

There is work being done to resolve https://github.com/netlify/pod-ecosystem-frameworks/issues/305 but for local development, the mock geo data is missing for `longitude`, `latitude`, and `timezone`.

### PR DESCRIPTION
**Pull request by nickytonline**
🎉 Thanks for submitting a pull request! 🎉

#### Summary

Adds missing mock geo data for local development. This can be merged before https://github.com/netlify/pod-ecosystem-frameworks/issues/305 is completed.

Fixes #5232
Relates to https://github.com/netlify/pod-ecosystem-frameworks/issues/305

---

For us to review and ship your PR efficiently, please perform the following steps:

- [x] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [x] Update or add tests (if any source code was changed or added) 🧪
- [ ] Update or add documentation (if features were changed or added) 📝
- [x] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

### CODE REVIEW

**Review by orinokai — DISMISSED** [review]
LGTM 🚀

File: src/lib/geo-location.cjs [hunk 1]
```diff
@@ -19,12 +19,18 @@ const REQUEST_TIMEOUT = 1e4
...
+ * @property {string} timezone
  */
 
 const mockLocation = {
   city: 'San Francisco',
   country: { code: 'US', name: 'United States' },
   subdivision: { code: 'CA', name: 'California' },
+  longitude: 0,
+  latitude: 0,
+  timezone: 'Mock Timezone',
```
Comment (ascorbic) [inline src/lib/geo-location.cjs:33]: [pebble] Could I suggest using a real timezone (e.g. UTC) so that the mock data can be used in places that need a valid tz string.
