### PR TITLE
fix: verbose flag displays the necessary information

### LINKED ISSUE #778: verbose flag doesn't serve the purpose
**- Do you want to request a _feature_ or report a _bug_?**
bug report

**- What is the current behavior?**
We've the `--verbose` flag as part of `status` command which shows up local environment information useful while submitting bug reports. But it doesn't display the information as expected.

https://github.com/netlify/cli/blob/d54b500c548c0e45d9a496eec988726e23cb67da/src/commands/status/index.js#L78
Moving the above block just below the respective line would serve the purpose.
https://github.com/netlify/cli/blob/d54b500c548c0e45d9a496eec988726e23cb67da/src/commands/status/index.js#L12

**- If the current behavior is a bug, please provide the steps to reproduce.**
Type in `netlify status --verbose`
If you're logged in, the respective information is being displayed or else an appropriate warning shows up.

**- What is the expected behavior?**
`netlify status --verbose` displays local environment information.

### PR DESCRIPTION
**Pull request by jamesgeorge007**
**- Summary**
Made `verbose` flag to show up local environment information which wasn't the case before.
closes #778

**- Test plan**

**- Description for the changelog**
`--verbose` flag shows up information regarding the local environment when passed along with the `status` command.

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

File: src/commands/status/index.js [hunk 1]
```diff
@@ -10,6 +10,22 @@ class StatusCommand extends Command {
...
+ Environment Info   │
+────────────────────┘`)
+      const data = await envinfo.run({
+        System: ['OS', 'CPU'],
+        Binaries: ['Node', 'Yarn', 'npm'],
+        Browsers: ['Chrome', 'Edge', 'Firefox', 'Safari'],
+        npmGlobalPackages: ['netlify-cli']
+      })
+      this.log(data)
+      this.exit()
```
Comment (RaeesBhatti) [inline src/commands/status/index.js:26]: Why exit here?

Comment (jamesgeorge007) [reply src/commands/status/index.js]: Yeah, It would make sense to log rest of the status information.
