### PR TITLE
fix: fix a regression where the creation of a new github token failed inside the init command

### LINKED ISSUE #3588: Github authentication for `netlify init` is not working due to a regression.
**Describe the bug**

**To Reproduce**

1. remove the global `~/Library/Preferences/netlify/config.json`
2. run `netlify init` in a new project
3. Select Authentication via netlify app
4. Use Github as the authentication method.
5. It will fail with `401 Bad Credentials`

Regression was introduced with this change: https://github.com/netlify/cli/pull/3569/files#diff-f64dd88efec835a92fdd4fd9b786ef5faf32c0c732656935ec33a443efb2c912R39

The problem is that the return type of the `getGitHubToken` changed from `Promise<Record<string, string>>` to `Promsie<URLSearchParams>` which cannot be set inside the globalConfig.

Just to note (TypeScript would have prevented this)

**Expected behavior**

Authentication via Github should work

**CLI Output**

```
Adding deploy key to repository...
 ›   Error: Failed retrieving GitHub repository information with error: Bad credentials.
```

### PR DESCRIPTION
**Pull request by lukasholzer**
🎉 Thanks for submitting a pull request! 🎉

#### Summary

Fixes #3588

For us to review and ship your PR efficiently, please perform the following steps:

- [x] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [x] Update or add tests (if any source code was changed or added) 🧪
- [x] Update or add documentation (if features were changed or added) 📝
- [x] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

### CODE REVIEW

File: src/utils/gh-auth.js [hunk 1]
```diff
@@ -31,14 +31,26 @@ const promptForAuthMethod = async () => {
...
+ */
 const authWithNetlify = async () => {
   const port = await getPort({ port: SERVER_PORT })
   const { promise: deferredPromise, reject: deferredReject, resolve: deferredResolve } = createDeferred()
 
   const server = http.createServer(function onRequest(req, res) {
     const parameters = new URLSearchParams(req.url.slice(req.url.indexOf('?') + 1))
     if (parameters.get('token')) {
-      deferredResolve(parameters)
+      const recordOfParams = [...parameters].reduce((prev, [key, value]) => ({ ...prev, [key]: value }), {})
```
Comment (tinfoil-knight) [inline src/utils/gh-auth.js:52]: @lukasholzer While going through the fix for this bug yesterday, I found out that the `cli` repo already has a polyfill for `fromEntries` (which is what we're trying to do here).

You can use it like this:
`const fromEntries = require('@ungap/from-entries')`

`const recordOfParams = fromEntries([...parameters])`

Comment (lukasholzer) [reply src/utils/gh-auth.js:52]: thx for pointing out :)

File: src/lib/functions/form-submissions-handler.js [hunk 2]
```diff
@@ -38,7 +39,7 @@ const createFormSubmissionHandler = function ({ functionsRegistry, siteUrl }) {
         encoding: ct.parameters.charset,
       })
 
-      fields = getObjectFromParams(new URLSearchParams(bodyData.toString()))
+      fields = fromEntries([...new URLSearchParams(bodyData.toString())])
```
Comment (ehmicky) [inline src/lib/functions/form-submissions-handler.js:42]:
```suggestion
      fields = fromEntries(new URLSearchParams(bodyData.toString()))
```

[sand] Tiny simplification since `URLSearchParams()` is iterable and `Object.fromEntries()` can use iterables as argument.

File: src/utils/gh-auth.js [hunk 3]
```diff
@@ -31,14 +32,25 @@ const promptForAuthMethod = async () => {
...
+ */
 const authWithNetlify = async () => {
   const port = await getPort({ port: SERVER_PORT })
   const { promise: deferredPromise, reject: deferredReject, resolve: deferredResolve } = createDeferred()
 
   const server = http.createServer(function onRequest(req, res) {
     const parameters = new URLSearchParams(req.url.slice(req.url.indexOf('?') + 1))
     if (parameters.get('token')) {
-      deferredResolve(parameters)
+      deferredResolve(fromEntries([...parameters]))
```
Comment (ehmicky) [inline src/utils/gh-auth.js:53]:
```suggestion
      deferredResolve(fromEntries(parameters))
```

[sand] See above

File: src/utils/open-browser.js [hunk 4]
```diff
@@ -33,4 +33,4 @@ const openBrowser = async function ({ silentBrowserNoneError, url }) {
   }
 }
 
-module.exports = openBrowser
+module.exports = { openBrowser }
```
Comment (ehmicky) [inline src/utils/open-browser.js:36]: The following consumers should be updated with the new signature:

https://github.com/netlify/cli/blob/9165fe3e69b69dab015fdd930feed8ebec89181a/src/commands/addons/auth.js#L4

https://github.com/netlify/cli/blob/9165fe3e69b69dab015fdd930feed8ebec89181a/src/commands/deploy.js#L24

https://github.com/netlify/cli/blob/9165fe3e69b69dab015fdd930feed8ebec89181a/src/commands/dev/index.js#L20

https://github.com/netlify/cli/blob/9165fe3e69b69dab015fdd930feed8ebec89181a/src/commands/open/admin.js#L3

https://github.com/netlify/cli/blob/9165fe3e69b69dab015fdd930feed8ebec89181a/src/commands/open/site.js#L3

https://github.com/netlify/cli/blob/9165fe3e69b69dab015fdd930feed8ebec89181a/src/utils/command.js#L14

https://github.com/netlify/cli/pull/3592/files#diff-9f1c90587f2f1996609d5d02f01ef29eba18d163b06171d7b11a651376e40461R7

**Review by ehmicky — COMMENTED** [review]
Thanks @lukasholzer!

The automated tests seem to be failing, which might be related to.

File: src/utils/open-browser.js (hunk 4 above)
Comment (lukasholzer) [reply src/utils/open-browser.js:36]: Thx have overseen that 👍

**Review by ehmicky — APPROVED** [review]
