### PR TITLE
fix: fix framework server loading spinner ("Waiting for framework port")

### LINKED ISSUE #7124: Never ending "Waiting for framework" in 19.0.3
### Describe the bug

Since upgrading to 19.0.3, `netlify dev` is constantly showing the following message, with a spinner on the left:
```
⠦ Waiting for framework port 5173. This can be configured using the 'targetPort' property in the netlify.toml
```

Running the same command with 19.0.2 does not result in the same behaviour. In fact, the wait seems to be over pretty quickly:
```
✔ Waiting for framework port 5173. This can be configured using the 'targetPort' property in the netlify.toml
```
This is printed out before the message saying `Server now ready on http://localhost:8888`

### Steps to reproduce

1. Start in the root of my repo (apologies, this is a private project)
2. Upgrade netlify-cli to 19.0.3
3. Run `netlify dev`
4. Everything seems to be working fine, but the CLI keeps "waiting for framework port 5173"

### Configuration

```toml
[build]
command = "react-router build"
publish = "build/client"

[dev]
command = "react-router dev"
```

### Environment

```
  System:
    OS: macOS 15.3.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 3.13 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 23.10.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.9.2 - /usr/local/bin/npm
  npmGlobalPackages:
    netlify-cli: 19.0.3
```

### PR DESCRIPTION
**Pull request by serhalp**
### Summary

This is a regression in the loading spinner shown before "Waiting for framework port", introduced in 19.0.3.

See:
1. https://github.com/netlify/cli/pull/7026
2. https://github.com/netlify/cli/pull/7131
3. https://github.com/netlify/cli/issues/7124

Oops, I was really overthinking this. All this needs to do is, every time a chunk comes in from the underlying framework dev server, clear the spinner line, write the chunk, then resume the spinner.

This wasn't set up right at all, which was obfuscated by the erroneous use of `isSpinning`.

Fixes #7124.

Thank you @Florian-Mt for spotting the (embarrassing!) fix.

#### Before

Monosnap screencast 2025-05-01 08-05-27

#### After

Monosnap screencast 2025-05-01 08-03-20

### CODE REVIEW

File: src/utils/framework-server.ts [hunk 1]
```diff
@@ -68,7 +68,7 @@ export const startFrameworkServer = async function ({
         throw new Error(`Timed out waiting for port '${settings.frameworkPort}' to be open`)
       }
     }
-    stopSpinner({ error: false, spinner })
+    spinner.success()
```
Comment (serhalp) [inline src/utils/framework-server.ts:71]: We want to draw the ✔️, erase it

File: src/utils/shell.ts [hunk 2]
```diff
@@ -61,15 +61,9 @@ export const runCommand = (
...
-    stopSpinner({ error: false, spinner })
-  }
   const pipeDataWithSpinner = (writeStream: NodeJS.WriteStream, chunk: string | Uint8Array) => {
-    if (spinner?.isSpinning) {
-      spinner.clear()
-    }
+    // Clear the spinner, write the framework command line, then resume spinning
+    spinner?.clear()
     writeStream.write(chunk, () => {
       spinner?.spin()
```
Comment (serhalp) [inline src/utils/shell.ts:68]: I believe this still isn't quite right — spin() renders a single frame, but here we want to keep looping even when we aren't receiving chunks from the framework server.

But this fix is worth getting in now and I'll follow up when I get the full fix working.

Comment (serhalp) [reply src/utils/shell.ts:68]: (In that follow-up I'll also look into how we can add test coverage for this)

**Review by sarahetter — APPROVED** [review]
