### PR TITLE
fix: live tunnel arch issue

### LINKED ISSUE #3561: "netlify dev --live" error
This is what happens when I run "netlify dev --live".

      flexone@penguin:~/code/flatiron/projects/project-1-weather-app$ netlify dev --live
      ◈ Netlify Dev ◈
      ◈ Ignored general context env var: LANG (defined in process)
      ◈ No app server detected. Using simple static server
      ◈ Running static server from "project-1-weather-app"
      ◈ Functions server is listening on 46415
      
      ◈ Static server listening to 3999
          Error: Command failed with exit code 2: /home/flexone/.config/netlify/tunnel/bin/live-tunnel-client 
          version
          /home/flexone/.config/netlify/tunnel/bin/live-tunnel-client: 1: 
          /home/flexone/.config/netlify/tunnel/bin/live-tunnel-client: H1�H1��8P�8P��@P�@P��iF: not found
          /home/flexone/.config/netlify/tunnel/bin/live-tunnel-client: 1: 
          /home/flexone/.config/netlify/tunnel/bin/live-tunnel-client: ��: not found
          /home/flexone/.config/netlify/tunnel/bin/live-tunnel-client: 1: 
          /home/flexone/.config/netlify/tunnel/bin/live-tunnel-client: ELF: not found
          /home/flexone/.config/netlify/tunnel/bin/live-tunnel-client: 1: 
          /home/flexone/.config/netlify/tunnel/bin/live-tunnel-client: Syntax error: Unterminated quoted string

I've removed netlify-cli and reinstalled it, through npm, and I created a brand new site at netlify and ran "netlify init" to relink my project.

"netlify dev" works...

### PR DESCRIPTION
**Pull request by lukasholzer**
🎉 Thanks for submitting a pull request! 🎉

#### Summary

Fixes #3561

This will now stop working for debian arm64 so we need to build the image first before merging.

The matching PR for cross compiling the different CPU architectures https://github.com/netlify/live-tunnel/pull/112
---

For us to review and ship your PR efficiently, please perform the following steps:

- [x] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [x] Update or add tests (if any source code was changed or added) 🧪
- [x] Update or add documentation (if features were changed or added) 📝
- [x] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

### CODE REVIEW

File: src/lib/exec-fetcher.js [hunk 1]
```diff
@@ -1,13 +1,15 @@
 // @ts-check
 const path = require('path')
 const process = require('process')
+const { stringify } = require('querystring')
```
Comment (ehmicky) [inline src/lib/exec-fetcher.js:4]: [sand] What are your thoughts on using `new URL()` and `url.searchParams.set()` instead?
This is mostly equivalent, except it uses the DOM API instead of Node.js core API. What are your thoughts on this?

**Review by ehmicky — DISMISSED** [review]

File: src/lib/exec-fetcher.js (hunk 1 above)
Comment (lukasholzer) [reply src/lib/exec-fetcher.js:4]: Yea why not I don't have a preference to be honest -> is there any benefit?

Comment (ehmicky) [reply src/lib/exec-fetcher.js:4]: If we had more code to share with the front-end, it would be better. And Node.js has been moving in that direction lately of using more and more the DOM API, as opposed to to its own core Node.js modules (`URI`, `AbortSignal`, `EventTarget`, `globalThis`, ES modules, `Blob`, `ReadableStream`/`WritableStream`/`TransformStream`, `Worker`, Web Crypto, `performance`, `structuredClone`), which seems a good thing at a higher level, and is also closer to the direction Deno is heading.

However, this is more of a conceptual benefit in this case, since we do not intend to run this file anywhere but on a terminal in this case, so either way could work.

File: bin/run [hunk 2]
```diff
@@ -1,6 +1,7 @@
 #!/usr/bin/env node
 /* eslint-disable promise/prefer-await-to-then,promise/prefer-await-to-callbacks,eslint-comments/disable-enable-pair */
 const process = require('process')
+const { format } = require('util')
```
Comment (erezrokah) [inline bin/run:4]: Can we remove this line?

**Review by erezrokah — DISMISSED** [review]
This looks good to me.
I'll @ehmicky and @lukasholzer resolve https://github.com/netlify/cli/pull/4064/files#r786137881

**Comment by ehmicky** [comment]
https://github.com/netlify/cli/pull/4064/files#r786137881 was more of a side note, please feel free to dismiss! :)

**Comment by lukasholzer** [comment]
@erezrokah who is the best one to review the matching PR in the live tunnel repo? netlify/live-tunnel#112

File: src/lib/exec-fetcher.js (hunk 1 above)
Comment (ehmicky) [reply src/lib/exec-fetcher.js:4]: I just realized this too: `querystring` is marked as "legacy" [in the Node.js documentation](https://nodejs.org/api/querystring.html#query-string).

**Comment by lukasholzer** [comment]
just tried the new binary for arm64 on my m1 mac and it works 🥳

**Comment by lukasholzer** [comment]
@charliegerard I hope it works now on the raspberry pi ;) 

I added now following CPU architectures: https://github.com/netlify/live-tunnel-client/releases/tag/v0.2.10

**Comment by charliegerard** [comment]
omg thank you so much for working on it!! 😃 🙌  Right on time for a talk I have to give next week 🥳 I'll test it a bit later today!

File: src/lib/exec-fetcher.js (hunk 1 above)
Comment (lukasholzer) [reply src/lib/exec-fetcher.js:4]: I'll change it for you ;)

**Review by erezrokah — APPROVED** [review]
