### PR TITLE
fix(headers): add support for consistent * wildcard

### LINKED ISSUE #1148: Error: invalid rule (A path rule cannot contain anything after * token)
**Describe the bug**

I'm getting the following error from my __header file when running netlify dev

`Error: invalid rule (A path rule cannot contain anything after * token)`

**Configuration**

the content of my __header file looks like this:

```bash
/*
  X-Frame-Options: SAMEORIGIN
  X-XSS-Protection: 1; mode=block
  cache-control: max-age=31536000
  cache-control: no-cache
  cache-control:  no-store
  cache-control: must-revalidate
/*.js
  cache-control: max-age=31536000
/*.css
  cache-control: max-age=31536000
/*.woff
  cache-control: max-age=31536000
```

adding to https://play.netlify.com/headers, this is deemed valid

**Expected behavior**

I would expect `netlify dev` to run and apply these header rules

**CLI Output**

`netlify dev` fail with the following error; `Error: invalid rule (A path rule cannot contain anything after * token)`

### PR DESCRIPTION
**Pull request by ctjlewis**
### Summary
The CLI's current behavior is to only allow the asterisk wildcard `*` at the end of a rule. This PR aims to add support for wildcard which matches Netlify's deploy logic, which does not seem to have the same restriction.
 
1. See https://github.com/netlify/next-on-netlify/issues/151
2. Closes #1148

### Test plan

Tests were updated in `headers.test.js`. More robust testing should likely be added before merging.

### Changelog

```none
Previously, (*) wildcards had to appear at the end of a rule path, as in /path/to/dir/*. The CLI now supports the asterisk wildcard at any part of the rule, i.e. /test/*/test/*/test.
```

### CODE REVIEW

File: src/utils/headers.js [hunk 1]
```diff
@@ -3,45 +3,131 @@ const fs = require('fs')
...
+     */
+    index += 1
   }
-
-  return false
+  /**
+   * If no mismatch was found, the rule matches the target path.
+   */
+  return true
 }
```
Comment (ctjlewis) [inline src/utils/headers.js:104]: Rewrote `matchPaths` logic to accept `*` wildcard at places other than the final `rulePart`.

File: src/utils/headers.js [hunk 2]
```diff
@@ -3,45 +3,131 @@ const fs = require('fs')
...
+  for (const [rule, headers] of Object.entries(rules)) {
+    /**
+     * If the rule matches the math, assign the respective headers.
+     */
+    const isMatch = matchPaths(rule, path)
+    if (isMatch) Object.assign(pathObject, headers)
+  }
+  /** Return matched headers. */
+  return pathObject
 }
```
Comment (ctjlewis) [inline src/utils/headers.js:131]: Rewrote illegible `Array.reduce()` call; added comments. Will save future contributors a headache.

File: src/utils/headers.js [hunk 3]
```diff
@@ -63,11 +149,6 @@ const parseHeadersFile = function (filePath) {
 
     if (line.startsWith(TOKEN_COMMENT) || line.length === 0) continue
     if (line.startsWith(TOKEN_PATH)) {
-      if (line.includes('*') && line.indexOf('*') !== line.length - 1) {
-        throw new Error(
-          `invalid rule (A path rule cannot contain anything after * token) at line: ${index}\n${lines[index]}\n`,
-        )
-      }
       path = line
```
Comment (ctjlewis) [inline src/utils/headers.js:152]: Remove `invalid rule (A path rule cannot contain anything after * token)` error

File: src/utils/headers.test.js [hunk 4]
```diff
@@ -21,6 +21,20 @@ const headers = [
...
+   */
+  {
+    path: '/*/_next/static/chunks/*',
+    headers: ['cache-control: public', 'cache-control: max-age=31536000', 'cache-control: immutable'],
+  },
+  {
+    path: '/directory/*/test.html',
+    headers: ['X-Frame-Options: test'],
+  },
 ]
```
Comment (ctjlewis) [inline src/utils/headers.test.js:39]: Add tests for newly-supported header syntax

File: src/utils/headers.test.js [hunk 5]
```diff
@@ -38,7 +52,14 @@ test.after(async (t) => {
   await t.context.builder.cleanupAsync()
 })
 
-test('_headers: validate correct parsing', (t) => {
+/**
+ * Pass if we can load the test headers without throwing an error.
+ */
+test('_headers: syntax validates as expected', (t) => {
+  parseHeadersFile(path.resolve(t.context.builder.directory, '_headers'))
+})
```
Comment (ctjlewis) [inline src/utils/headers.test.js:60]: Ensure new syntax does not throw

File: src/utils/headers.test.js [hunk 6]
```diff
@@ -55,6 +76,12 @@ test('_headers: validate correct parsing', (t) => {
     '/:placeholder/index.html': {
       'X-Frame-Options': ['SAMEORIGIN'],
     },
+    '/*/_next/static/chunks/*': {
+      'cache-control': ['public', 'max-age=31536000', 'immutable'],
+    },
```
Comment (ctjlewis) [inline src/utils/headers.test.js:81]: Add tests for newly-supported header syntax

File: src/utils/headers.test.js [hunk 7]
```diff
@@ -55,6 +76,12 @@ test('_headers: validate correct parsing', (t) => {
...
+    '/directory/*/test.html': {
+      'X-Frame-Options': ['test'],
+    },
```
Comment (ctjlewis) [inline src/utils/headers.test.js:84]: Add tests for newly-supported header syntax

File: src/utils/headers.test.js [hunk 8]
```diff
@@ -83,4 +110,12 @@ test('_headers: rulesForPath testing', (t) => {
...
     'X-Frame-Thing': ['SAMEORIGIN'],
   })
+  t.deepEqual(objectForPath(rules, '/placeholder/_next/static/chunks/placeholder'), {
+    'X-Frame-Thing': ['SAMEORIGIN'],
+    'cache-control': ['public', 'max-age=31536000', 'immutable'],
+  })
+  t.deepEqual(objectForPath(rules, '/directory/placeholder/test.html'), {
+    'X-Frame-Thing': ['SAMEORIGIN'],
+    'X-Frame-Options': ['test'],
+  })
```
Comment (ctjlewis) [inline src/utils/headers.test.js:120]: Add tests for newly-supported header syntax

**Comment by ctjlewis** [comment]
If anyone has any suggestions regarding the PR label check, please let me know! I'm not sure what to do to clear that up - I thought the `feat:` tag was enough 😭

(also cc @lindsaylevine)

File: src/utils/headers.js [hunk 9]
```diff
@@ -3,45 +3,127 @@ const fs = require('fs')
...
+      return false
     }
   }
-
-  return false
+  /**
+   * If no mismatch was found, the rule matches the target path.
+   */
+  return true
 }
```
Comment (ctjlewis) [inline src/utils/headers.js:100]: Rewrote `matchPaths` logic to accept `*` wildcard at places other than the final `rulePart`.

**Comment by lindsaylevine** [comment]
this looks amazing @ctjlewis !!! the label thing has to be one of the `type: ${something}` labels 😺 . i added both bug and feat cause i think it qualifies as both, lol. but thanks for being so thorough!! looks like the windows 14.x tests timed out..? 🤔 i'll leave it to @ehmicky and @erezrokah from here :)

**Comment by ctjlewis** [comment]
Turns out this logic is like half redundant so hopefully nobody sees it before I clean it up 😂

File: src/utils/headers.js [hunk 10]
```diff
@@ -3,45 +3,116 @@ const fs = require('fs')
...
+       */
+      return false
+    } else if (noMoreRuleParts) {
+      /**
+       * If we have made it through all of the rules without finding a mismatch,
+       * the rule matches the path.
+       */
+      return true
     }
   }
```
Comment (ctjlewis) [inline src/utils/headers.js:84]: Rewriting `matchPaths` was the bulk of the work here. It now supports the asterisk at any position, and handles trailing asterisk wildcards as expected (`/path/*` matches `/path`, `/path/to/dir`, etc.)

File: src/utils/headers.test.js [hunk 11]
```diff
@@ -83,4 +110,54 @@ test('_headers: rulesForPath testing', (t) => {
...
+   * index >= pathParts.length && index >= ruleParts.length check.
+   */
+  t.assert(matchPaths('/path/to/dir/*', '/path/to/dir'))
+  /**
+   * Mixed (*) and (:placeholder) wildcards.
+   */
+  t.assert(matchPaths('/path/*/to/:placeholder/:placeholder/*', '/path/placeholder/to/placeholder/dir/test'))
+  t.assert(matchPaths('/path/*/:placeholder', '/path/to/dir'))
+  t.assert(matchPaths('/path/:placeholder/:placeholder/*', '/path/to/dir/one/two/three'))
 })
```
Comment (ctjlewis) [inline src/utils/headers.test.js:163]: Headers tests should focus on testing `matchPaths`, since that is where the algorithm logic is. I tried to cover almost all cases here. Please let me know if I missed any.

**Comment by ctjlewis** [comment]
This will currently match `/path/to/dir/:placeholder` with `/path/to/dir`, which we do not want as I understand it (that would effectively be `:placeholder` matching an empty dir `/`).

This "spec" is not well-worded nor detailed, and it only says:

> Paths can contain `*` or `:placeholders`. A `:placeholder` matches anything except `/`, while a `*` matches anything. 

I definitely knew we should take this to mean `/` does not match `/:placeholder` but does match `/*`, but does the `/` in the quote provided above refer also to nonexistent directory, i.e., should `/path/to/dir` match `/path/to/dir/:placeholder` where it definitely matches `/path/to/dir/*`?

Once we get clarification on this, this will be ready to finalize.

File: src/utils/headers.js [hunk 12]
```diff
@@ -3,45 +3,117 @@ const fs = require('fs')
...
+      /**
+       * If a mismatch is found, the rule does not match.
+       */
+      return false
+    } else if (noMoreRuleParts) {
+      /**
+       * If we have made it through all of the rules without finding a mismatch,
+       * the rule matches the path.
+       */
+      return true
```
Comment (ctjlewis) [inline src/utils/headers.js:83]: Refactoring `matchPaths` was the bulk of the work here. Be wary of `/path/to/dir` matching `/path/to/dir/:placeholder` under this logic (though `/path/:placeholder` will not match `/path/to/dir`).

File: src/utils/headers.test.js [hunk 13]
```diff
@@ -83,4 +110,63 @@ test('_headers: rulesForPath testing', (t) => {
...
+  t.assert(matchPaths('/path/to/dir/:placeholder', '/path/to/dir'))
+  t.assert(matchPaths('/path/to/dir/*/:placeholder', '/path/to/dir/test'))
+  /**
+   * Mixed (*) and (:placeholder) wildcards.
+   */
+  t.assert(matchPaths('/path/*/to/:placeholder/:placeholder/*', '/path/placeholder/to/placeholder/dir/test'))
+  t.assert(matchPaths('/path/*/:placeholder', '/path/to/dir'))
+  t.assert(matchPaths('/path/:placeholder/:placeholder/*', '/path/to/dir/one/two/three'))
+  t.assert(matchPaths('/path/to/dir/*/:placeholder/test', '/path/to/dir/asterisk/placeholder/test'))
 })
```
Comment (ctjlewis) [inline src/utils/headers.test.js:172]: Test `matchPaths` logic the most rigorously given it is the bulk of the matching algorithm.

File: src/utils/headers.js [hunk 14]
```diff
@@ -3,45 +3,117 @@ const fs = require('fs')
...
     }
   }
```
Comment (ctjlewis) [inline src/utils/headers.js:85]: Refactoring `matchPaths` was the bulk of the work here.

Be wary of `/path/to/dir` matching `/path/to/dir/:placeholder` *and* `/path/to/dir/*` under this logic (though `/path/:placeholder` will not match `/path/to/dir`, where `/path/*` will).

**Comment by ctjlewis** [comment]
Just tested: This version of `netlify dev` correctly handles the `next-on-netlify` rule `/*/_next/static/chunks/*`, from https://github.com/netlify/next-on-netlify/issues/151, which inspired this PR.

The `netlify dev` page finally loads and displays the content!

**Review by erezrokah — COMMENTED** [review]
Hi @ctjlewis, this is great work! Thank for the fix and those comments & tests look awesome 🚀 

I'm going to look into our production logic to verify we're not missing anything here before I merge this.

**Comment by ctjlewis** [comment]
Absolutely @erezrokah - if you can share any clarification you find on the production logic, I'd appreciate it. The Custom Headers documentation could use a teeny bit more context IMO (mostly just regarding the `/path/to/dir/:placeholder` vs `/path/to/dir` case).

**Comment by erezrokah** [comment]
Hi @ctjlewis sorry for the delay. I added another commit for the headers parsing to make it more consistent with our production logic.
I think it should also make it easier to understand the expected structure.

I'll follow up on the headers matching as well. After finishing the latter I'll open an issue for our docs team to clarify https://docs.netlify.com/routing/headers/#syntax-for-the-headers-file.

**Comment by erezrokah** [comment]
> Once we get clarification on this, this will be ready to finalize.

`/path/to/dir/:placeholder` **should not** match `/path/to/dir`
`/path/to/dir/*` **should** match `/path/to/dir`

I also added some tests for `/*test`.

The last changes use a regular expression instead of the previous approach - that's much closer to the production logic (it's not pretty though).

**Review by erezrokah — APPROVED** [review]
@ctjlewis thanks again for helping us to clarify this.

I've opened a follow up issue to our docs team

**Review by eduardoboucas — APPROVED** [review]
This looks great — thanks @ctjlewis! 🙌🏻

**Comment by ctjlewis** [comment]
> `/path/to/dir/:placeholder` **should not** match `/path/to/dir`
> `/path/to/dir/*` **should** match `/path/to/dir`

Super sorry for the delay in response! One note:

https://github.com/netlify/cli/blob/5166b97ef25e76102bbacbed3d72521aa1b271a4/src/utils/headers.test.js#L192

I wonder if `/path/to/dir/*/:placeholder` would match `/path/to/dir`, when it technically... should *not?*

No idea, not just trying to make more work, just couldn't not notice it lol.

**Comment by erezrokah** [comment]
> I wonder if `/path/to/dir/*/:placeholder` would match `/path/to/dir`, when it technically... should _not?_
Another interesting one :)

Well it is matched by our prod logic:
https://github.com/erezrokah/netlify-build-reproductions/blob/7408e60fdaa2d83780c3664474ab813127a6475e/public/_headers#L1
https://6013edd04e27200008943118--erez-build-reproductions.netlify.app/path/to/dir/test/

I'll add that use case to our docs issue, thanks!
