### PR TITLE
fix(command-dev): replace deprecated static-server dep by fastify-static

### LINKED ISSUE #4511: chore(deps): remove usage of the static-server dependency
We use [static-server](https://github.com/nbluis/static-server/blob/84999917193f664c205efd587934bc6ea361fa78/README.md) to simulate a static server a part of the `ntl dev` command.

About 2 months ago it was deprecated and repo archived, see https://github.com/nbluis/static-server/blob/84999917193f664c205efd587934bc6ea361fa78/README.md.

~~We should replace it with another package, possible https://expressjs.com/en/starter/static-files.html as we already have `express` as a dependency.~~

See comment: https://github.com/netlify/cli/issues/4511#issuecomment-1087635077

### PR DESCRIPTION
**Pull request by tinfoil-knight**
🎉 Thanks for submitting a pull request! 🎉

#### Summary

Fixes #4511 

The [static-server](https://github.com/nbluis/static-server/blob/84999917193f664c205efd587934bc6ea361fa78/README.md) dependency which is currently being used by the `netlify dev` command is now deprecated. This PR intends to replace the dependency with [fastify-static](https://github.com/fastify/fastify-static) (recommended by @lukasholzer).

---

For us to review and ship your PR efficiently, please perform the following steps:

- [x] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [x] Update or add tests (if any source code was changed or added) 🧪
- [ ] Update or add documentation (if features were changed or added) 📝
- [ ] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**
🦖

### CODE REVIEW

File: src/commands/dev/dev.mjs [hunk 1]
```diff
@@ -55,16 +54,26 @@ import { createDevExecCommand } from './dev-exec.mjs'
...
+      res.setHeader('X-Powered-by', 'netlify-dev')
     },
   })
-
-  await promisify(server.start.bind(server))()
+   
+  server.setNotFoundHandler((_req, res) => {
+    res.sendFile('404.html', settings.dist)
+  })
+  server.addHook('onRequest', (req, reply) => {
```
Comment (tinfoil-knight) [inline src/commands/dev/dev.mjs:69]: https://www.fastify.io/docs/latest/Reference/Hooks/#onrequest

File: src/commands/dev/dev.mjs [hunk 2]
```diff
@@ -55,16 +54,26 @@ import { createDevExecCommand } from './dev-exec.mjs'
...
+    const validMethods = ['GET', 'HEAD']
+    if (!validMethods.includes(req.method)) {
+      reply.code(405).send()
+      return reply
+    }
```
Comment (tinfoil-knight) [inline src/commands/dev/dev.mjs:74]: Adapted from https://github.com/nbluis/static-server/blob/84999917193f664c205efd587934bc6ea361fa78/server.js#L163-L164 since the `should rewrite POST request if content-type is missing and not crash dev server` test ([source](https://github.com/netlify/cli/blob/e3db3144d77f7a3c7abc9b2fe803d701242492f4/tests/integration/0.command.dev.test.cjs#L240-L241)) depends on the correct status code.

File: src/commands/dev/dev.mjs (hunk 1 above)
Comment (tinfoil-knight) [inline src/commands/dev/dev.mjs:69]: [fastify.io/docs/latest/Reference/Hooks/#onrequest](https://www.fastify.io/docs/latest/Reference/Hooks/#onrequest)

**Comment by tinfoil-knight** [comment]
Relevant Documentation Links for the `fastify` & `@fastify/static` packages.

- https://www.fastify.io/docs/latest/Reference/Hooks/#onrequest
- https://www.fastify.io/docs/latest/Reference/Server/#setnotfoundhandler

- https://github.com/fastify/fastify-static#setheaders

File: src/commands/dev/dev.mjs [hunk 3]
```diff
@@ -55,16 +54,26 @@ import { createDevExecCommand } from './dev-exec.mjs'
...
-    name: 'netlify-dev',
-    port: settings.frameworkPort,
-    templates: {
-      notFound: path.join(settings.dist, '404.html'),
+  const server = Fastify()
+  server.register(fastifyStatic, {
+    root: settings.dist,
+    // eslint-disable-next-line no-unused-vars
+    setHeaders: (res, _path, _stat) => {
+      res.setHeader('X-Powered-by', 'netlify-dev')
```
Comment (tinfoil-knight) [inline src/commands/dev/dev.mjs:62]: The `name: 'netlify-dev'` configuration option in `static-server` sets the `X-Powered-by` header.

Ref:
https://github.com/nbluis/static-server/blob/84999917193f664c205efd587934bc6ea361fa78/server.js#L47

File: src/commands/dev/dev.mjs [hunk 4]
```diff
@@ -55,16 +55,29 @@ import { createDevExecCommand } from './dev-exec.mjs'
...
-    templates: {
-      notFound: path.join(settings.dist, '404.html'),
+  const server = Fastify()
+  server.register(fastifyStatic, {
+    root: path.resolve(settings.dist),
+    // eslint-disable-next-line no-unused-vars
+    setHeaders: (res, _path, _stat) => {
+      res.setHeader('X-Powered-by', 'netlify-dev')
     },
+    etag: false,
```
Comment (tinfoil-knight) [inline src/commands/dev/dev.mjs:65]: ETag generation is disabled since the proxy already handles that.

File: src/commands/dev/dev.mjs [hunk 5]
```diff
@@ -55,16 +55,29 @@ import { createDevExecCommand } from './dev-exec.mjs'
...
-    name: 'netlify-dev',
-    port: settings.frameworkPort,
-    templates: {
-      notFound: path.join(settings.dist, '404.html'),
+  const server = Fastify()
+  server.register(fastifyStatic, {
+    root: path.resolve(settings.dist),
+    // eslint-disable-next-line no-unused-vars
+    setHeaders: (res, _path, _stat) => {
+      res.setHeader('X-Powered-by', 'netlify-dev')
```
Comment (tinfoil-knight) [inline src/commands/dev/dev.mjs:63]: The `name: 'netlify-dev'` configuration option in `static-server` sets the `X-Powered-by` header.

**Comment by tinfoil-knight** [comment]
**Change in Headers**

- For successful request & unsuccessful request with 404.html:
`last-modified`, `accept-ranges`, `cache-control` (public, max-age=0) were added.

- For unsuccessful request without 404.html:
`x-powered-by`, `transfer-encoding` (chunked) was removed.
	
- `content-type` for all requests with a file in response have changed from `text/html` to `text/html; charset=UTF-8`

The only significant change here IMO is the `cache-control` header. Do we want to do anything about the other headers?

Note: In production Netlify, `cache-control` is `public, max-age=0, must-revalidate`.

File: src/commands/dev/dev.mjs [hunk 6]
```diff
@@ -55,16 +55,29 @@ import { createDevExecCommand } from './dev-exec.mjs'
...
-    name: 'netlify-dev',
-    port: settings.frameworkPort,
-    templates: {
-      notFound: path.join(settings.dist, '404.html'),
-    },
+  const server = Fastify()
+  const rootPath = path.resolve(settings.dist)
+  server.register(fastifyStatic, {
+    root: rootPath,
+    etag: false,
```
Comment (tinfoil-knight) [inline src/commands/dev/dev.mjs:62]: ETag generation is disabled since the proxy already handles that.

File: src/commands/dev/dev.mjs [hunk 7]
```diff
@@ -55,16 +55,29 @@ import { createDevExecCommand } from './dev-exec.mjs'
...
+    lastModified: false,
   })
 
-  await promisify(server.start.bind(server))()
+  server.setNotFoundHandler((_req, res) => {
+    res.code(404).sendFile('404.html', rootPath)
+  })
+
+  server.addHook('onRequest', (req, reply, done) => {
+    reply.header('X-Powered-by', 'netlify-dev')
```
Comment (tinfoil-knight) [inline src/commands/dev/dev.mjs:72]: The name: 'netlify-dev' configuration option in `static-server` used to set the `X-Powered-by` header.

Comment (tinfoil-knight) [inline src/commands/dev/dev.mjs:72]: The `name: 'netlify-dev'` configuration in `static-server` used to set the `X-Powered-by` header.

**Review by danez — DISMISSED** [review]
Awesome. Happy new year.
I was already thinking about doing this. and even replacing express everywhere, but that would be a much bigger task I think.

**Review by danez — APPROVED** [review]

**Comment by tinfoil-knight** [comment]
> Awesome. Happy new year.

Happy new year to you too @danez. It was fun working w/ you & other folks on the Netlify team past year.
